### ISSUE TITLE
 "Expand only Comments" is confusing

### ISSUE THREAD

**Issue by sopotov** [mrlacey/CollapseComments#11] opened 2020-05-05 15:56 UTC
### Installed product versions
- Visual Studio: Microsoft Visual Studio Community 2019 Version 16.5.4
- This extension: 1.7

### Description
Expand Only Comments collapses methods

### Steps to recreate
1. Right-Click text editor
2. Select Expand Only Comments
3. Collapses methods

### Current behavior
Doesn't not collapse comments

### Expected behavior
Supposed to expand comments and didn't touch anything else

text of the c# class:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestSelectMasterSql
{
	// class
	// comment
	class Class1
	{
		// method
		// comment
		void Method()
		{
			// first
			// comment
			var i = 1;
			i = 2;
			// second
			// comment
			i = 3;
			i = 4;
			i = 5;
		}
	}
}

![image](https://user-images.githubusercontent.com/36208734/81305390-44898980-904c-11ea-9d7b-f4ec8039f410.png)

**Comment by mrlacey** [comment] 2020-05-05 19:48
Aaah.
It is no longer (for me at least) collapsing a comment if it is at the top of the file.
It does collapse using statements and other comment blocks further down in the file.

@sopotov  is this what you're seeing?

**Comment by mrlacey** [comment] 2020-05-05 19:52
Oops. found some other comment formats it's not catching.
@sopotov what file type are you seeing the failure in? And can you share the comment (or the file)?

**Comment by mrlacey** [comment] 2020-05-05 20:01
I've found a bug and pushed a new version (v1.5) to the marketplace that should fix it.
If you can share what isn't working for you I'll test against that as well and fix anything else if necessary.

Alternatively, if you can verify that v1.5 fixes this for you I'll close this out.

**Comment by sopotov** [comment] 2020-05-06 13:15
Matt,
I've installed version 1.5. Here is the results:
1. Original code

2. After Collapse Comments. Note it didn't collapse comments in Method

3. After Expand Only Comments - for some reason it collapsed whole class


Regards,Serge 

    On Tuesday, May 5, 2020, 04:02:15 p.m. EDT, Matt Lacey <notifications@github.com> wrote:  
 
 


I've found a bug and pushed a new version (v1.5) to the marketplace that should fix it.
If you can share what isn't working for you I'll test against that as well and fix anything else if necessary.

Alternatively, if you can verify that v1.5 fixes this for you I'll close this out.

**Comment by mrlacey** [comment] 2020-05-06 13:44
> 2. After Collapse Comments. Note it didn't collapse comments in Method

Can you share the method?
What language?
How is the comment formatted? Is it a multi-line comment? (like below)

```cs
            /* A multi-line comment
             * 
             */
```

> 3. After Expand Only Comments - for some reason it collapsed whole class 

Can you share the class definition?
(From the example below, I want `public class MainViewModel : Observable`)


```cs
    /// <summary>
    /// ViewModel for the main page.
    /// </summary>
    public class MainViewModel : Observable
    {
        public MainViewModel()
        {
            /* A multi-line comment
             * 
             */

            ...
        }
    }
```

**Comment by sopotov** [comment] 2020-05-06 15:52
Matt,
It looks like you don't see pictures in my message. Do you?
Regards,Serge 

    On Wednesday, May 6, 2020, 09:44:43 a.m. EDT, Matt Lacey <notifications@github.com> wrote:  
 
 


   
   - After Collapse Comments. Note it didn't collapse comments in Method


Can you share the method?
What language?
How is the comment formatted? Is it a multi-line comment? (like below)
            /* A multi-line comment
             * 
             */
   
   - After Expand Only Comments - for some reason it collapsed whole class


Can you share the class definition?
(From the example below, I want public class MainViewModel : Observable)
    /// <summary>
    /// ViewModel for the main page.
    /// </summary>
    public class MainViewModel : Observable
    {
        public MainViewModel()
        {
            /* A multi-line comment
             * 
             */

            ...
        }
    }

**Comment by mrlacey** [comment] 2020-05-06 15:55
> Matt, It looks like you don't see pictures in my message. Do you? Regards,Serge 

Nope. 
If you just reply to the email, GitHub updates the issue with the text but images are lost.

If you post (paste) them on the issue (https://github.com/mrlacey/CollapseComments/issues/11) then they'll be visible

**Comment by sopotov** [comment] 2020-05-06 20:25
Matt,
I've pasted pictures to issue #11
Regards,Serge 

    On Wednesday, May 6, 2020, 11:55:40 a.m. EDT, Matt Lacey <notifications@github.com> wrote:  
 
 



Matt, It looks like you don't see pictures in my message. Do you? Regards,Serge


Nope.
If you just reply to the email, GitHub updates the issue with the text but images are lost.

If you post (paste) them on the issue (#11) then they'll be visible

**Comment by mrlacey** [comment] 2020-05-07 11:06
@sopotov thank you for your patience and for taking the time to provide the information I have asked for.

The good news is that I believe I have solved both issues.

**Comments not collapsing**

It appears this isn't working because of another setting in Visual Studio.
When "Show outlining for comments and preprocessor regions" is not selected it is not possible to collapse the comments.

**Tools > Options > Text editor > C# > Advanced**
![image](https://user-images.githubusercontent.com/189547/81287034-fa0f0980-9059-11ea-8842-424929ba9b36.png)

The reason for this behavior is that this extension works by looking at the outlined regions and then collapsing or expanding them. It doesn't look for the comments directly.


**The whole class being collapsed**

Based on your image, I identified that you are likely using tabs for indentation. The code was previously using spaces as part of the way it identified what to expand or collapse. I'd forgotten about tabs. :(
The good news is that version 1.7 is now available from the marketplace and works with both tabs and spaces.

**Comment by sopotov** [comment] 2020-05-07 14:23
Matt,
Version 1.7 collapses methods now :(I've updated issue #11
Regards,Serge 

    On Wednesday, May 6, 2020, 04:25:45 p.m. EDT, Sergiy Sopotov <sopotov@yahoo.com> wrote:  
 
 Matt,
I've pasted pictures to issue #11
Regards,Serge 

    On Wednesday, May 6, 2020, 11:55:40 a.m. EDT, Matt Lacey <notifications@github.com> wrote:  
 
 



Matt, It looks like you don't see pictures in my message. Do you? Regards,Serge


Nope.
If you just reply to the email, GitHub updates the issue with the text but images are lost.

If you post (paste) them on the issue (#11) then they'll be visible

**Comment by mrlacey** [comment] 2020-05-07 18:24
Ok.
So, as can be seen from the below image (notice the [lack of] plus and minus boxes in the left margin), VS doesn't automatically support outlining for repeated single-line comments unless they start with triple slashes.
As this extension relies on the automatic outlining this explains the behavior that's being seen.

I'll see what can be done about this.

![image](https://user-images.githubusercontent.com/189547/81330275-c5ba3e00-9097-11ea-8a8a-4f6bc675c7a8.png)

**Comment by sopotov** [comment] 2020-05-07 22:36
Matt,
I understand the issue about the -+ boxes - it is VS problem. What I'm trying to report is collapse of the method on Expand Comments in V1.7 (in V1.5 it collapsed class)
Note I'm using tabs for indents

Отправлено из Yahoo Почты для Android 
 
  чт, 7 мая 2020 в 14:24 Matt Lacey<notifications@github.com> написал(-а):   


Ok.
So, as can be seen from the below image (notice the [lack of] plus and minus boxes in the left margin), VS doesn't automatically support outlining for repeated single-line comments unless they start with triple slashes.
As this extension relies on the automatic outlining this explains the behavior that's being seen.

I'll see what can be done about this.

**Comment by mrlacey** [comment] 2020-05-08 14:30
OK. So the issue is that, when invoking `Expand Only Comments` a method is collapsed even when it contains comments.

I think the correct behavior here is that the method should not be collapsed if it contains multi-line comments (which should themselves be expanded.)

A method (or equivalent) that only contains single-line comments should be collapsed.

**Comment by mrlacey** [comment] 2020-05-14 17:07
All changes related to this were included in v1.8, which is available now. :)

**Comment by sopotov** [comment] 2020-05-15 00:07
Thank you 😊

 
 
  чт, 14 мая 2020 в 13:07 Matt Lacey<notifications@github.com> написал(-а):   


All changes related to this were included in v1.8, which is available now. :)

**Comment by Cleroth** [comment] 2022-04-01 01:32
@mrlacey It looks like this is happening again--but maybe not for the same reasons.

Example code:

```cpp
void Foo()
{
	// stuff
	// this and that
	// bla bla

	auto reenable_items = [&]
	{
		for(auto i : Iterate(total))
		{
			const u8 idx = items_idx[i];
			auto * item  = player->_items[idx];
			ASSERT(item);
			item->_disabled = false;
		}
	};

	for(int i = 0; i < 100; ++i)
	{
		"oh no";
		Foo();
	}
}
```

The lambda and the for loop are being collapsed.

With `Text Editor -> C/C++ -> View -> Outline Statement Blocks` set to `false`, the for loop doesn't get collapsed, but the lambda still does.

**Comment by mrlacey** [comment] 2022-04-01 17:13
@Cleroth I'll investigate

**Comment by mrlacey** [comment] 2022-04-01 21:12
> @mrlacey It looks like this is happening again--but maybe not for the same reasons.
> 
> Example code:
> 
> ```c++
> void Foo()
> {
> 	// stuff
> 	// this and that
> 	// bla bla
> 
> 	auto reenable_items = [&]
> 	{
> 		for(auto i : Iterate(total))
> 		{
> 			const u8 idx = items_idx[i];
> 			auto * item  = player->_items[idx];
> 			ASSERT(item);
> 			item->_disabled = false;
> 		}
> 	};
> 
> 	for(int i = 0; i < 100; ++i)
> 	{
> 		"oh no";
> 		Foo();
> 	}
> }
> ```
> 
> The lambda and the for loop are being collapsed.
> 
> With `Text Editor -> C/C++ -> View -> Outline Statement Blocks` set to `false`, the for loop doesn't get collapsed, but the lambda still does.

After investigation, I can't see how what you're describing is linked to this extension. 
The extension does no custom outlining for C++ files, and the additional outlining it does do is not related to anything that could do what you are seeing.
The exact same behavior is also experienced when the extension isn't installed.

It sounds as though this is either a bug within the C++ tooling or ambiguity over whether the lambda in your example should be classified as a statement block or not. (I don't know enough about the official definitions of the C++ language to say.)
I suggest you report it as a bug in the handling of lambdas or request more outlining control at https://developercommunity.visualstudio.com/

This is also different from what was described in this issue previously so I'm going to close.

**Comment by Cleroth** [comment] 2022-04-01 21:26
@mrlacey The bug isn't that they're collapsable. The bug is that `Expand Only Comments` collapses them. That's why I posted here... From what I understand, it's only supposed to expand comments, but it is currently collapsing the things I mentioned, like the lambda and other blocks.

Technically the behaviour I actually want is the "Collapse to Definitions" from Visual Studio, but without collapsing comments, which I was able to get with this extension (by combining the two). This is no longer possible due to it collapsing other things.

**Comment by mrlacey** [comment] 2022-04-01 21:38
> @mrlacey The bug isn't that they're collapsable. The bug is that `Expand Only Comments` collapses them. That's why I posted here... From what I understand, it's only supposed to expand comments, but it is currently collapsing the things I mentioned, like the lambda and other blocks.
> 
> Technically the behaviour I actually want is the "Collapse to Definitions" from Visual Studio, but without collapsing comments, which I was able to get with this extension (by combining the two). This is no longer possible due to it collapsing other things.

As per the feature description: "expands all comments and closes all other areas"

It is doing what it's supposed to.

I guess the confusion is around the command's name. 

It sounds like it would be useful to add a new option: "Expand comments" which only opens comment blocks (is not already open) and doesn't do anything else.
**Does this sound like a useful addition?**

**Comment by Cleroth** [comment] 2022-04-02 02:17
Yes, that would be useful. Even more useful would be to have a "Collapse to Definitions" like VS's but that doesn't collapse comments, as it stands I have to perform two actions to do what I want, when I'd rather it only be one.

**Comment by mrlacey** [comment] 2022-04-02 19:27
> Yes, that would be useful. Even more useful would be to have a "Collapse to Definitions" like VS's but that doesn't collapse comments, as it stands I have to perform two actions to do what I want, when I'd rather it only be one.

I've used calling two commands to achieve this too.

The way "Expand only Comments" currently works is kind of a hybrid of the two.
It expands all comments and then collapses anything that doesn't have a comment inside it.

It seems this isn't what's wanted and is confusing.

Instead of this I think it should be replaced with two other commands.
One will expand any currently collapsed comments and do nothing else.
One will collapse to definitions (using the built-in command--hopefully) and then open any comments for the collapsed items. 

Precise implementations to be determined.

**Comment by mrlacey** [comment] 2022-04-06 11:57
I expect I'll be motivated to look at the conditional execution of individual jobs next time I'm anxiously waiting for a set of PR checks to run 😉

**Comment by mrlacey** [comment] 2022-04-17 21:02
> One will collapse to definitions (using the built-in command--hopefully) and then open any comments for the collapsed items.

This bit is proving tricky. Trying to reuse the existing command and then making other changes isn't working as expected. Further investigation is needed.

**Comment by mrlacey** [comment] 2024-02-10 10:56
This seems to all be working as expected in the latest version.

If not, I recommend opening a new issue with specific details. (I had to reread this thread several times to try and understand it all)

**Closed as completed by mrlacey** 2024-02-10 10:56 UTC
Labels: bug
