### ISSUE TITLE
Toggling Does Not Work in 2022 17.8.1

### ISSUE THREAD

**Issue by zacharylayne** [mrlacey/CollapseComments#33] opened 2023-11-28 02:55 UTC
### Installed product versions
- Visual Studio: Community 2022 (64-bit) 17.8.1
- This extension: 2.5

### Description
Toggling comments does not work.

### Steps to recreate
1. Install extension.
2. Select all.
3. Press CTRL-M, CTRL-F

This issue persists when:
* All other extensions are disabled,
* Visual Studio is reinstalled.
* All other keyboard commands for this extension have been removed,
* The toggle keyboard command is remapped (for example, CTRL-M, CTRL-C),
* Toggling is selected from the context menu.

### Current behavior
Toggling comment expansion does not work.

### Expected behavior
Toggling comment expansion should work.

**Comment by mrlacey** [comment] 2023-11-28 12:55
Someone else reported this separately and we weren't able to find a consistent repo.
We eventually found that it did start working but it was as if the extension took a very long time to load or VS took ages before allowing the shortcut to do anything.

I'll look again.

**Comment by zacharylayne** [comment] 2023-12-04 05:14
I appreciate the response. If it helps, it DID work up until a week ago before I uninstalled VS, scrubbed a bunch of extensions, and reinstalled.

Any way this could be a bug with the latest Visual Studio releases?

**Comment by mrlacey** [comment] 2023-12-04 13:10
This only started happening with 17.8 
but not sure if it's something broken in VS (in which case I'd expect a lot of other extensions and functionality to break)
Or, I'm doing something "odd" that only shows up as a result of changes that happened in 17.8

Either way, I need to find time to do a deep investigation.... :(

**Comment by LarryAultman** [comment] 2024-01-13 12:38
I am experiencing the same behavior. I have VS2022 17.8.4. the ctrl M-K collapses it all. ctrl A-M-E expands everything.

**Comment by HexadigmSystems** [comment] 2024-01-31 12:56
Similar issue in VS2022_(17.8.5) but only recently installed it and your extension (2.5.1). Using your extension in _VS2019_ for a long time without issue though (kudos to you!). Issue in VS2022 strange though, Ctrll+M, Ctrl+C doesn't work (works from the context menu though), but if I change it to something else like Ctrl+M, Ctrl+Z (arbitrarily chosen), it does work. Restoring it to Ctrll+M, Ctrl+C again and it stops working again (maybe a conflict with something else assigned to Ctrll+M, Ctrl+C in my environment perhaps?). Tried uninstalling and reinstalling but same problem.

Ctrl+M, Ctrl+D works without issue.

Both Ctrl+M, Ctrl+F and its context menu collapse comments but doesn't expand them again (if that's what it's supposed to do - never use it normally).

Ctrl+M, Ctrl+E not working, but context menu is

FWIW I'm the (extension) developer of [this](https://www.hexadigm.com/) so lots of my own extension experience going back many years. Not sure what might be the cause of your issue though (obscure situation without digging into it but wouldn't surprise me if it's VS, as I've encountered numerous bugs over the years).

**Comment by mrlacey** [comment] 2024-02-01 23:37
Sorry this has taken so long. This thread has also gotten a bit side-tracked too.

Having done some investigation, here's what I've discovered.

1. Yes, toggling is broken. The internal logic doesn't correctly handle using toggle to expand a comment that is currently collapsed. I'm hoping to have a fix out for this next week.
2. The "`ctrl`+`M`, `ctrl`+`C`" combination is highly popular. If there is something else installed (workload or other extension) that registers to use this any attempt to use that shortcut just does nothing. If in this situation, you can manually change the shortcut keys. See details at https://learn.microsoft.com/en-us/visualstudio/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio?view=vs-2022#customize-a-keyboard-shortcut
    a. I'm considering changing the default shortcut keys to avoid such issues in the future....

**Comment by zacharylayne** [comment] 2024-02-02 00:01
I was able to fix it. The problem for me it seemed were hotkey conflicts. It wasn't extremely straightforward to fix, because there were multiple hotkeys conflicting with each other. I remember deleted the conflicting hotkeys from global, text editor, and C# editor and toggling worked.

**Comment by mrlacey** [comment] 2024-02-02 09:59
Some upvotes for this would be appreciated: https://developercommunity.visualstudio.com/t/Detecting-and-reporting-conflicting-hotk/10576876?port=1025&fsid=19aef27c-10b1-4e5c-a766-aaf256df55b1&ref=native&refTime=1706867902134&refUserId=91c2bc46-c9e1-43fd-92b1-4ce8bbfc1b78

**Comment by HexadigmSystems** [comment] 2024-02-02 18:09
@mrlacey  Appreciate all your efforts! (and upvoted as requested)

**Comment by mrlacey** [comment] 2024-02-08 09:15
HotKey conflicts will explain why a command works from the context menu but not from the hot keys / shortcut.

v2.6 (just released) fixes a bug where the "Toggle" command didn't always work as it should.

**Closed as completed by mrlacey** 2024-02-08 09:15 UTC

**Comment by HexadigmSystems** [comment] 2024-02-08 14:59
Hi Matt,

Downloaded the latest version (2.6) and _Ctrl+M, Ctrl+F_ mostly stable but not always (using VS 17.8.5). Some comments not collapsing sometimes when they should be (while most others are). I say "_sometimes_" since after playing around with the various hotkeys, it starts working again. Couldn't determine any pattern though. Moreover, on one specific occasion, after expanding one particular comment that wasn't respecting _Ctrl+M, Ctrl+F_, which looks like this ('.' below representing more occurrences of //):

////////////////////////////////////////////
//
//
.
.
.
////////////////////////////////////////////

It erroneously expanded to the following (one extra line of forward slashes added at the top!). It wasn't a phantom line (still there after saving, closing, and reloading the file):

////////////////////////////////////////////
////////////////////////////////////////////
//
//
.
.
.
////////////////////////////////////////////

No idea if issue is in your code or MSFT's (extra line issue maybe MSFT's I suspect since I assume you wouldn't be doing anything to add an extra line), but something is occasionally unstable (sorry if I've alarmed you but FWIW it seems to be stable most of the time - hard to recreate it).

I'm attaching two C++ files from my own repository [here](https://github.com/HexadigmAdmin/FunctionTraits) (the ones where I encountered the problem). The attached files are the latest I'm still working on, not yet pushed but likely soon (they contain the latest updates but do compile if it makes any difference - probably not). They contain a *lot* of comments though ("_TypeTraits.h_" the much bigger file), so maybe you can play around with them and see if you can reproduce the issue. You''ll need to rename their extensions from "_.txt_" back to "_.h_" (Github doesn't allow "_.h_" files to be uploaded). Just add them to any C++ project (they constitute the entire project documented at the above link).

[CompilerVersions.txt](https://github.com/mrlacey/CollapseComments/files/14210752/CompilerVersions.txt)
[TypeTraits.txt](https://github.com/mrlacey/CollapseComments/files/14210753/TypeTraits.txt)

**Comment by suugbut** [comment] 2024-12-09 20:29
I just installed it and does NOT work at all.

**Comment by mrlacey** [comment] 2024-12-10 09:37
> I just installed it and does NOT work at all.

Have you checked for Hot key conflicts? (see [above](https://github.com/mrlacey/CollapseComments/issues/33#issuecomment-1922486558))
